import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Sidebar from '../components/Sidebar';

export default function Home() {
  return (
    
    <div>
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {/* <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@800&display=swap" rel="stylesheet"></link> */}
      {/* <Head>
        <title>Felix</title>
        <meta name="description" content="help in meeting your goals" />
      </Head>
      <Header />
      <div className={styles.mainContainer}>
        <Sidebar />
      </div> */}
    </div>
  )
}
